planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      use_astar: True  # Enable A* search algorithm
      allow_unknown: True
      tolerance: 1.0
